from __future__ import annotations

from typing import Protocol
from uuid import UUID

from pdf_remediation.domain import Artifact, Job, Run


class ArtifactStore(Protocol):
    def put(self, key: str, content: bytes, media_type: str) -> str: ...
    def get(self, uri: str) -> bytes: ...


class Repository(Protocol):
    def add_job(self, job: Job) -> None: ...
    def get_job(self, job_id: UUID) -> Job | None: ...
    def list_jobs(self) -> list[Job]: ...
    def update_job(self, job: Job) -> None: ...

    def add_run(self, run: Run) -> None: ...
    def get_run(self, run_id: UUID) -> Run | None: ...
    def list_runs_for_job(self, job_id: UUID) -> list[Run]: ...
    def update_run(self, run: Run) -> None: ...

    def add_artifact(self, artifact: Artifact) -> None: ...
    def list_artifacts_for_job(self, job_id: UUID) -> list[Artifact]: ...
