from __future__ import annotations

from typing import Protocol
from uuid import UUID

from pdf_remediation.domain import (
    Artifact,
    Batch,
    Experiment,
    Job,
    PipelineRun,
    ReviewItem,
    StageExecution,
)


class Repository(Protocol):
    def create_batch(self, batch: Batch) -> Batch: ...
    def update_batch(self, batch: Batch) -> Batch: ...
    def get_batch(self, batch_id: UUID) -> Batch | None: ...
    def list_batches(self) -> list[Batch]: ...
    def create_job(self, job: Job) -> Job: ...
    def update_job(self, job: Job) -> Job: ...
    def get_job(self, job_id: UUID) -> Job | None: ...
    def list_jobs(self, batch_id: UUID | None = None) -> list[Job]: ...
    def create_experiment(self, experiment: Experiment) -> Experiment: ...
    def update_experiment(self, experiment: Experiment) -> Experiment: ...
    def get_experiment(self, experiment_id: UUID) -> Experiment | None: ...
    def list_experiments(self) -> list[Experiment]: ...
    def create_run(self, run: PipelineRun) -> PipelineRun: ...
    def update_run(self, run: PipelineRun) -> PipelineRun: ...
    def get_run(self, run_id: UUID) -> PipelineRun | None: ...
    def list_runs(self, job_id: UUID) -> list[PipelineRun]: ...
    def create_stage_execution(self, execution: StageExecution) -> StageExecution: ...
    def update_stage_execution(self, execution: StageExecution) -> StageExecution: ...
    def list_stage_executions(self, run_id: UUID) -> list[StageExecution]: ...
    def create_review_item(self, item: ReviewItem) -> ReviewItem: ...
    def update_review_item(self, item: ReviewItem) -> ReviewItem: ...
    def get_review_item(self, item_id: UUID) -> ReviewItem | None: ...
    def list_review_items(self, job_id: UUID | None = None) -> list[ReviewItem]: ...
    def create_artifact(self, artifact: Artifact) -> Artifact: ...
    def get_artifact(self, artifact_id: UUID) -> Artifact | None: ...
    def list_artifacts(self, job_id: UUID, run_id: UUID | None = None) -> list[Artifact]: ...


class ArtifactStore(Protocol):
    def put(self, key: str, content: bytes, content_type: str) -> None: ...
    def get(self, key: str) -> bytes: ...
    def exists(self, key: str) -> bool: ...
    def delete(self, key: str) -> None: ...
